### ISSUE TITLE
Panic: repeated oneOf causes Panic

### ISSUE THREAD

**Issue by phumberdroz** [rodaine/protogofakeit#5]
This causes a panic. 
```
message User {
  repeated Friend friends = 8;
}

message Friend {
  oneof platform_details {
    Human human = 1;
    Animal animal = 2;
  }
}
```

<details>
  <summary>Stack trace</summary>
  Stack Trace:

  ```stacktrace
panic: type mismatch: cannot convert nil to message [recovered]
	panic: type mismatch: cannot convert nil to message

goroutine 6 [running]:
testing.tRunner.func1.2({0x104a054a0, 0x140002850a0})
	/Users/phumberdroz/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.darwin-arm64/src/testing/testing.go:1631 +0x3c0
testing.tRunner.func1()
	/Users/phumberdroz/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.darwin-arm64/src/testing/testing.go:1634 +0x57c
panic({0x104a054a0?, 0x140002850a0?})
	/Users/phumberdroz/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.darwin-arm64/src/runtime/panic.go:770 +0xf0
google.golang.org/protobuf/reflect/protoreflect.Value.Message({{}, 0x0, 0x0, 0x0})
	/Users/phumberdroz/go/pkg/mod/google.golang.org/protobuf@v1.33.0/reflect/protoreflect/value_union.go:346 +0x108
google.golang.org/protobuf/internal/impl.(*messageConverter).GoValueOf(0x140002844d0, {{}, 0x0, 0x0, 0x0})
	/Users/phumberdroz/go/pkg/mod/google.golang.org/protobuf@v1.33.0/internal/impl/convert.go:439 +0x48
google.golang.org/protobuf/internal/impl.fieldInfoForOneof.func4({0x14000093dc0}, {{}, 0x0, 0x0, 0x0})
	/Users/phumberdroz/go/pkg/mod/google.golang.org/protobuf@v1.33.0/internal/impl/message_reflect_field.go:122 +0x220
google.golang.org/protobuf/internal/impl.(*messageState).Set(0x14000093dc0, {0x104abf860, 0x140001e0600}, {{}, 0x0, 0x0, 0x0})
	/Users/phumberdroz/go/pkg/mod/google.golang.org/protobuf@v1.33.0/internal/impl/message_reflect_gen.go:91 +0xec
github.com/rodaine/protogofakeit.(*protoFaker).fakeOneofs(0x1400023cb60, 0x1, {0x104abf028, 0x14000093dc0}, {0x104abf4c0, 0x140000c7760})
	/Users/phumberdroz/projects/spectrm/sandbox/protogofakeit/protogofakeit.go:161 +0x3e8
github.com/rodaine/protogofakeit.(*protoFaker).fake(0x1400023cb60, 0x1, {0x104abf028, 0x14000093dc0})
	/Users/phumberdroz/projects/spectrm/sandbox/protogofakeit/protogofakeit.go:142 +0x1d8
github.com/rodaine/protogofakeit.(*protoFaker).fakeFieldValue(0x1400023cb60, 0x0, {{}, 0x104a92e40, 0x14000093dc0, 0x0}, {0x104abf860, 0x140000be700}, 0x0, 0x1)
	/Users/phumberdroz/projects/spectrm/sandbox/protogofakeit/protogofakeit.go:231 +0x484
github.com/rodaine/protogofakeit.(*protoFaker).fakeList(0x1400023cb60, 0x0, {0x104abf860, 0x140000be700}, 0x0, {0x104ab25d8, 0x14000269a70})
	/Users/phumberdroz/projects/spectrm/sandbox/protogofakeit/protogofakeit.go:307 +0x14c
github.com/rodaine/protogofakeit.(*protoFaker).fakeFieldValue(0x1400023cb60, 0x0, {{}, 0x104a77ac0, 0x14000269a70, 0x0}, {0x104abf860, 0x140000be700}, 0x0, 0x0)
	/Users/phumberdroz/projects/spectrm/sandbox/protogofakeit/protogofakeit.go:220 +0x1f0
github.com/rodaine/protogofakeit.(*protoFaker).fakeField(0x1400023cb60, 0x0, {0x104abf028, 0x14000093540}, {0x104abf860, 0x140000be700})
	/Users/phumberdroz/projects/spectrm/sandbox/protogofakeit/protogofakeit.go:200 +0x14c
github.com/rodaine/protogofakeit.(*protoFaker).fakeFields(0x1400023cb60, 0x0, {0x104abf028, 0x14000093540}, {0x104abf4c0, 0x140000c7688})
	/Users/phumberdroz/projects/spectrm/sandbox/protogofakeit/protogofakeit.go:184 +0xe8
github.com/rodaine/protogofakeit.(*protoFaker).fake(0x1400023cb60, 0x0, {0x104abf028, 0x14000093540})
	/Users/phumberdroz/projects/spectrm/sandbox/protogofakeit/protogofakeit.go:145 +0x218
github.com/rodaine/protogofakeit.(*protoFaker).FakeProto(0x1400023cb60, {0x104aad8a8, 0x14000093540})
	/Users/phumberdroz/projects/spectrm/sandbox/protogofakeit/protogofakeit.go:135 +0x60
github.com/rodaine/protogofakeit_test.TestName(0x140001a1380)
	/Users/phumberdroz/projects/spectrm/sandbox/protogofakeit/example_test.go:20 +0xbc
testing.tRunner(0x140001a1380, 0x104aa8b00)
	/Users/phumberdroz/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.darwin-arm64/src/testing/testing.go:1689 +0x1a8
created by testing.(*T).Run in goroutine 1
	/Users/phumberdroz/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.darwin-arm64/src/testing/testing.go:1742 +0x668
  ```
  
</details>

**Comment by rodaine** [comment]
Thanks for the report, @phumberdroz! Will take a look
